//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.FinalAnswer;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "HistoryYes"
	when
    	q : Question(getText() == "History?", getAnswer() == "YES")
	then
    
	    FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getBookList().add("Wolf Hall; Hilary Mantel");
		finalAnswer.setEnd(true);
		insert(finalAnswer);
end

rule "HistoryNo"
    //include attributes such as "salience" here...
    when
        q : Question(getText() == "History?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("Something Family?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
