//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.FinalAnswer;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "IdentityYes"
	when
    	q : Question(getText() == "Identity?", getAnswer() == "YES")
	then
    
	    FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getBookList().add("White Teeth; Zadie Smith");
	    finalAnswer.getBookList().add("The Brief Life of Oscar Wao; Junot Diaz");
	    finalAnswer.getBookList().add("The Namesake; Jhumpa Lahiri");	    
	   	finalAnswer.setEnd(true);
		insert(finalAnswer);
end

rule "IdentityNo"
    //include attributes such as "salience" here...
    when
        q : Question(getText() == "Identity?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("Magical Realism?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
