//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.FinalAnswer;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "InspirationYes"
	when
    	q : Question(getText() == "Inspiration?", getAnswer() == "YES")
	then
    
	    FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getBookList().add("The Last Lecture; Randy Pausch");
	   	finalAnswer.setEnd(true);
		insert(finalAnswer);
end

rule "InspirationNo"
    //include attributes such as "salience" here...
    when
        q : Question(getText() == "Inspiration?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("U.S. Goverment?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
