//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "LiteraryFictionYes"

   when
    q : Question(getText() == "Literary fiction?", getAnswer() == "YES")
   then
	    Question newQuestion = new Question("Dystopia?");
	    newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);
end

rule "LiteraryFictionNo"
    when
        q : Question(getText() == "Literary fiction?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("Fiction for Kids?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
