//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "LookingForNonfictionYes"

   when
    q : Question(getText() == "Looking for Nonfiction?", getAnswer() == "YES")
   then
	    Question newQuestion = new Question("Memoirs?");
	    newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);
end

rule "LookingForNonfictionNo"
    when
        q : Question(getText() == "Looking for Nonfiction?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("In need of Advice?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
