//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.FinalAnswer;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "RomanceYes"
	when
    	q : Question(getText() == "Romance?", getAnswer() == "YES")
	then
    
	    FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getBookList().add("The Other Boleyn Girl; Philippa Gregory");
	    finalAnswer.getBookList().add("Snow Flower and the Secret Fan; Lisa See");		
		finalAnswer.setEnd(true);
		insert(finalAnswer);
end

rule "RomanceNo"
    //include attributes such as "salience" here...
    when
        q : Question(getText() == "Romance?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("Time Travel?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
