//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.FinalAnswer;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "SomethingFamilyYes"
	when
    	q : Question(getText() == "Something Family?", getAnswer() == "YES")
	then
    
	    FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getBookList().add("The Corrections; Jonathan Franzen");
	    finalAnswer.getBookList().add("Middlesex; Jeffrey Eugenides");
		finalAnswer.setEnd(true);
		insert(finalAnswer);
end

rule "SomethingFamilyNo"
    //include attributes such as "salience" here...
    when
        q : Question(getText() == "Something Family?", getAnswer() == "NO")
    then
        Question newQuestion = new Question("Looking for Mystery?");
       	newQuestion.addYesNo();
	    Print.showQuestion(newQuestion);
		insert(newQuestion);

end
