//created on: 2018-12-06
package rules;
import com.sample.Question;
import com.sample.FinalAnswer;
import com.sample.Print;
import java.util.Scanner;
import java.util.ArrayList;


//list any import classes here.



//declare any global variables here




rule "SuspenseYes"
	when
    	q : Question(getText() == "Suspense?", getAnswer() == "YES")
	then
    
	    FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getBookList().add("Gone Girl; Gilian Flynn");
	    finalAnswer.getBookList().add("The Da Vinci Code; Dan Brown");
		finalAnswer.setEnd(true);
		insert(finalAnswer);
end

rule "SuspenseNo"
    //include attributes such as "salience" here...
    when
        q : Question(getText() == "Suspense?", getAnswer() == "NO")
    then
        FinalAnswer finalAnswer = new FinalAnswer();
	    finalAnswer.getOut();
		finalAnswer.setEnd(true);
		insert(finalAnswer);

end
